/* This file is autogenerated, do not edit*/
#include "ScopeComp_automoc.dir/moc_mainwindow_ED5CM347FTOB2P.cpp"
#include "ScopeComp_automoc.dir/moc_panel_JKA7SQT54UOHO5.cpp"
#include "ScopeComp_automoc.dir/moc_plot_IM47OQEQVGZXLO.cpp"
