# DO NOT EDIT THIS FILE!
#
# Python module SpreadSheet__POA generated by omniidl

import omniORB
omniORB.updateModule("SpreadSheet__POA")

# ** 1. Stub files contributing to this module
import SpreadSheet_idl

# ** 2. Sub-modules

# ** 3. End
