cd /d %~dp0
cmake ./ -G %VC% -DEIGEN_DIRECTORIY=%EIGEN_DIRECTORIY% -DODE_DIRECTORIY=%ODE_DIRECTORIY% -DQWT_DIRECTORIY=%QWT_DIRECTORIY% -D CMAKE_INSTALL_PREFIX="C:/OpenRTM-aist" ./
cmake --build . --config %BuildType%
