# DO NOT EDIT THIS FILE!
#
# Python module Writer generated by omniidl

import omniORB
omniORB.updateModule("Writer")

# ** 1. Stub files contributing to this module
import Writer_idl

# ** 2. Sub-modules

# ** 3. End
