# Install script for directory: C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/OpenRTM-aist")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "component" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/Debug/ECandStateSharedComposite.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/Release/ECandStateSharedComposite.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/MinSizeRel/ECandStateSharedComposite.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/RelWithDebInfo/ECandStateSharedComposite.lib")
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "component" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE SHARED_LIBRARY FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/Debug/ECandStateSharedComposite.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE SHARED_LIBRARY FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/Release/ECandStateSharedComposite.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE SHARED_LIBRARY FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/MinSizeRel/ECandStateSharedComposite.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE SHARED_LIBRARY FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/RelWithDebInfo/ECandStateSharedComposite.dll")
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "component" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE EXECUTABLE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/Debug/ECandStateSharedCompositeComp.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE EXECUTABLE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/Release/ECandStateSharedCompositeComp.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE EXECUTABLE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/MinSizeRel/ECandStateSharedCompositeComp.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/bin" TYPE EXECUTABLE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/RelWithDebInfo/ECandStateSharedCompositeComp.exe")
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends.cmake"
         "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/CMakeFiles/Export/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite" TYPE FILE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/CMakeFiles/Export/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite" TYPE FILE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/CMakeFiles/Export/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite" TYPE FILE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/CMakeFiles/Export/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite" TYPE FILE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/CMakeFiles/Export/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/components/lib/ECandStateSharedComposite" TYPE FILE FILES "C:/workspace/MSMTest/SettingRTSystem/Composite/ECandStateSharedComposite/src/CMakeFiles/Export/components/lib/ECandStateSharedComposite/ECandStateSharedCompositeDepends-release.cmake")
  endif()
endif()

