#!/bin/sh
cd `dirname $0`

sh AbsFunction/build_all.sh
sh ArmController/build_all.sh
sh Backlash/build_all.sh
sh Bias/build_all.sh
sh CapturePresentation/build_all.sh
sh ConstantValue/build_all.sh
sh ControlEducatorVehicle/build_all.sh
sh ConvertImage/build_all.sh
sh CoulombAndViscousFriction/build_all.sh
sh Crawl_Gait_Controller/build_all.sh
sh DataBaseInPut/build_all.sh
sh DataBaseOutPut/build_all.sh
sh DeadZone/build_all.sh
sh DemuxFunction/build_all.sh
sh Derivative/build_all.sh
sh EncodeData/build_all.sh
sh EncodeSeqData/build_all.sh
sh EV3SampleCPP/build_all.sh
sh EV3SamplePy/build_all.sh
sh ExcelRTCpy/build_all.sh
sh FloatSeqToVelocity/build_all.sh
sh Foot_Position_Controller/build_all.sh
sh Four_legged_Robot_Simulator/build_all.sh
sh Gain/build_all.sh
sh IfElse/build_all.sh
sh Integrator/build_all.sh
sh Intermittent_Crawl_Gait_Controller/build_all.sh
sh MinMaxFunction/build_all.sh
sh MovieDataBaseInputRTC/build_all.sh
sh MuxFunction/build_all.sh
sh MyFirstComponent/build_all.sh
sh MySecondComponent/build_all.sh
sh NineAxisSensor_RT_USB/build_all.sh
sh PIDController/build_all.sh
sh Polynomial/build_all.sh
sh PowerPointControlpy/build_all.sh
sh PresentationView/build_all.sh
sh ProductFunction/build_all.sh
sh PulseGenerator/build_all.sh
sh RampFunction/build_all.sh
sh RandomNumber/build_all.sh
sh RasPiMouseController_DistanceSensor/build_all.sh
sh RaspberryPiMouseController_Joystick/build_all.sh
sh RaspberryPiMouseGUI/build_all.sh
sh RasPiMouseSampleCPP/build_all.sh
sh RasPiMouseSamplePy/build_all.sh
sh RateLimiter/build_all.sh
sh Relay/build_all.sh
sh RMC/build_all.sh
sh RobotArmSimulator/build_all.sh
sh Saturation/build_all.sh
sh Scope/build_all.sh
sh SignFunction/build_all.sh
sh SineWave/build_all.sh
sh SqrtFunction/build_all.sh
sh StepFunction/build_all.sh
sh SumFunction/build_all.sh
sh testEC/build_all.sh
sh testECpy/build_all.sh
sh TrigonometricFunction/build_all.sh
sh Trot_Gait_Controller/build_all.sh
sh UnaryMinus/build_all.sh
sh UniformRandomNumber/build_all.sh
sh WordControlpy/build_all.sh
sh WrapToZero/build_all.sh
