cd /d %~dp0


cmd /c AbsFunction\build_all.bat
cmd /c ArmController\build_all.bat
cmd /c Backlash\build_all.bat
cmd /c Bias\build_all.bat
cmd /c CapturePresentation\build_all.bat
cmd /c ConstantValue\build_all.bat
cmd /c ControlEducatorVehicle\build_all.bat
cmd /c ConvertImage\build_all.bat
cmd /c CoulombAndViscousFriction\build_all.bat
cmd /c Crawl_Gait_Controller\build_all.bat
cmd /c DataBaseInPut\build_all.bat
cmd /c DataBaseOutPut\build_all.bat
cmd /c DeadZone\build_all.bat
cmd /c DemuxFunction\build_all.bat
cmd /c Derivative\build_all.bat
cmd /c EncodeData\build_all.bat
cmd /c EncodeSeqData\build_all.bat
cmd /c EV3SampleCPP\build_all.bat
cmd /c EV3SamplePy\build_all.bat
cmd /c ExcelRTCpy\build_all.bat
cmd /c FloatSeqToVelocity\build_all.bat
cmd /c Foot_Position_Controller\build_all.bat
cmd /c Four_legged_Robot_Simulator\build_all.bat
cmd /c Gain\build_all.bat
cmd /c IfElse\build_all.bat
cmd /c Integrator\build_all.bat
cmd /c Intermittent_Crawl_Gait_Controller\build_all.bat
cmd /c MinMaxFunction\build_all.bat
cmd /c MovieDataBaseInputRTC\build_all.bat
cmd /c MuxFunction\build_all.bat
cmd /c MyFirstComponent\build_all.bat
cmd /c MySecondComponent\build_all.bat
cmd /c NineAxisSensor_RT_USB\build_all.bat
cmd /c PIDController\build_all.bat
cmd /c Polynomial\build_all.bat
cmd /c PowerPointControlpy\build_all.bat
cmd /c PresentationView\build_all.bat
cmd /c ProductFunction\build_all.bat
cmd /c PulseGenerator\build_all.bat
cmd /c RampFunction\build_all.bat
cmd /c RandomNumber\build_all.bat
cmd /c RaspberryPiMouseController_DistanceSensor\build_all.bat
cmd /c RaspberryPiMouseController_Joystick\build_all.bat
cmd /c RaspberryPiMouseGUI\build_all.bat
cmd /c RasPiMouseSampleCPP\build_all.bat
cmd /c RasPiMouseSamplePy\build_all.bat
cmd /c RateLimiter\build_all.bat
cmd /c Relay\build_all.bat
cmd /c RMC\build_all.bat
cmd /c RobotArmSimulator\build_all.bat
cmd /c Saturation\build_all.bat
cmd /c Scope\build_all.bat
cmd /c SignFunction\build_all.bat
cmd /c SineWave\build_all.bat
cmd /c SqrtFunction\build_all.bat
cmd /c StepFunction\build_all.bat
cmd /c SumFunction\build_all.bat
cmd /c testEC\build_all.bat
cmd /c testECpy\build_all.bat
cmd /c TrigonometricFunction\build_all.bat
cmd /c Trot_Gait_Controller\build_all.bat
cmd /c UnaryMinus\build_all.bat
cmd /c UniformRandomNumber\build_all.bat
cmd /c WordControlpy\build_all.bat
cmd /c WrapToZero\build_all.bat
