# Python stubs generated by omniidl from SpreadSheet.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"SpreadSheet.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"SpreadSheet.idl")


# typedef ... StringSeq
class StringSeq:
    _NP_RepositoryId = "IDL:StringSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0__GlobalIDL.StringSeq = StringSeq
_0__GlobalIDL._d_StringSeq  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0__GlobalIDL._ad_StringSeq = (omniORB.tcInternal.tv_alias, StringSeq._NP_RepositoryId, "StringSeq", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0__GlobalIDL._tc_StringSeq = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._ad_StringSeq)
omniORB.registerType(StringSeq._NP_RepositoryId, _0__GlobalIDL._ad_StringSeq, _0__GlobalIDL._tc_StringSeq)
del StringSeq

# typedef ... StringList
class StringList:
    _NP_RepositoryId = "IDL:StringList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0__GlobalIDL.StringList = StringList
_0__GlobalIDL._d_StringList  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:StringSeq:1.0"], 0)
_0__GlobalIDL._ad_StringList = (omniORB.tcInternal.tv_alias, StringList._NP_RepositoryId, "StringList", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:StringSeq:1.0"], 0))
_0__GlobalIDL._tc_StringList = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._ad_StringList)
omniORB.registerType(StringList._NP_RepositoryId, _0__GlobalIDL._ad_StringList, _0__GlobalIDL._tc_StringList)
del StringList

# typedef ... FloatSeq
class FloatSeq:
    _NP_RepositoryId = "IDL:FloatSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0__GlobalIDL.FloatSeq = FloatSeq
_0__GlobalIDL._d_FloatSeq  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_float, 0)
_0__GlobalIDL._ad_FloatSeq = (omniORB.tcInternal.tv_alias, FloatSeq._NP_RepositoryId, "FloatSeq", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_float, 0))
_0__GlobalIDL._tc_FloatSeq = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._ad_FloatSeq)
omniORB.registerType(FloatSeq._NP_RepositoryId, _0__GlobalIDL._ad_FloatSeq, _0__GlobalIDL._tc_FloatSeq)
del FloatSeq

# typedef ... FloatList
class FloatList:
    _NP_RepositoryId = "IDL:FloatList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0__GlobalIDL.FloatList = FloatList
_0__GlobalIDL._d_FloatList  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:FloatSeq:1.0"], 0)
_0__GlobalIDL._ad_FloatList = (omniORB.tcInternal.tv_alias, FloatList._NP_RepositoryId, "FloatList", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:FloatSeq:1.0"], 0))
_0__GlobalIDL._tc_FloatList = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._ad_FloatList)
omniORB.registerType(FloatList._NP_RepositoryId, _0__GlobalIDL._ad_FloatList, _0__GlobalIDL._tc_FloatList)
del FloatList

#
# Start of module "SpreadSheet"
#
__name__ = "SpreadSheet"
_0_SpreadSheet = omniORB.openModule("SpreadSheet", r"SpreadSheet.idl")
_0_SpreadSheet__POA = omniORB.openModule("SpreadSheet__POA", r"SpreadSheet.idl")


# interface mSpreadSheet
_0_SpreadSheet._d_mSpreadSheet = (omniORB.tcInternal.tv_objref, "IDL:SpreadSheet/mSpreadSheet:1.0", "mSpreadSheet")
omniORB.typeMapping["IDL:SpreadSheet/mSpreadSheet:1.0"] = _0_SpreadSheet._d_mSpreadSheet
_0_SpreadSheet.mSpreadSheet = omniORB.newEmptyClass()
class mSpreadSheet :
    _NP_RepositoryId = _0_SpreadSheet._d_mSpreadSheet[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_SpreadSheet.mSpreadSheet = mSpreadSheet
_0_SpreadSheet._tc_mSpreadSheet = omniORB.tcInternal.createTypeCode(_0_SpreadSheet._d_mSpreadSheet)
omniORB.registerType(mSpreadSheet._NP_RepositoryId, _0_SpreadSheet._d_mSpreadSheet, _0_SpreadSheet._tc_mSpreadSheet)

# mSpreadSheet operations and attributes
mSpreadSheet._d_get_string = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), None)
mSpreadSheet._d_set_value = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_float), (), None)
mSpreadSheet._d_get_string_range = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:StringList:1.0"], ), None)
mSpreadSheet._d_set_value_range = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:FloatList:1.0"]), (), None)
mSpreadSheet._d_set_string = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
mSpreadSheet._d_set_string_range = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:StringList:1.0"]), (), None)

# mSpreadSheet object reference
class _objref_mSpreadSheet (CORBA.Object):
    _NP_RepositoryId = mSpreadSheet._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def get_string(self, *args):
        return self._obj.invoke("get_string", _0_SpreadSheet.mSpreadSheet._d_get_string, args)

    def set_value(self, *args):
        return self._obj.invoke("set_value", _0_SpreadSheet.mSpreadSheet._d_set_value, args)

    def get_string_range(self, *args):
        return self._obj.invoke("get_string_range", _0_SpreadSheet.mSpreadSheet._d_get_string_range, args)

    def set_value_range(self, *args):
        return self._obj.invoke("set_value_range", _0_SpreadSheet.mSpreadSheet._d_set_value_range, args)

    def set_string(self, *args):
        return self._obj.invoke("set_string", _0_SpreadSheet.mSpreadSheet._d_set_string, args)

    def set_string_range(self, *args):
        return self._obj.invoke("set_string_range", _0_SpreadSheet.mSpreadSheet._d_set_string_range, args)

omniORB.registerObjref(mSpreadSheet._NP_RepositoryId, _objref_mSpreadSheet)
_0_SpreadSheet._objref_mSpreadSheet = _objref_mSpreadSheet
del mSpreadSheet, _objref_mSpreadSheet

# mSpreadSheet skeleton
__name__ = "SpreadSheet__POA"
class mSpreadSheet (PortableServer.Servant):
    _NP_RepositoryId = _0_SpreadSheet.mSpreadSheet._NP_RepositoryId


    _omni_op_d = {"get_string": _0_SpreadSheet.mSpreadSheet._d_get_string, "set_value": _0_SpreadSheet.mSpreadSheet._d_set_value, "get_string_range": _0_SpreadSheet.mSpreadSheet._d_get_string_range, "set_value_range": _0_SpreadSheet.mSpreadSheet._d_set_value_range, "set_string": _0_SpreadSheet.mSpreadSheet._d_set_string, "set_string_range": _0_SpreadSheet.mSpreadSheet._d_set_string_range}

mSpreadSheet._omni_skeleton = mSpreadSheet
_0_SpreadSheet__POA.mSpreadSheet = mSpreadSheet
omniORB.registerSkeleton(mSpreadSheet._NP_RepositoryId, mSpreadSheet)
del mSpreadSheet
__name__ = "SpreadSheet"

#
# End of module "SpreadSheet"
#
__name__ = "_GlobalIDL"


#
# End of module "_GlobalIDL"
#
__name__ = "SpreadSheet_idl"

_exported_modules = ( "SpreadSheet", "_GlobalIDL")

# The end.
