/* This file is autogenerated, do not edit*/
#include "RMC_automoc.dir/moc_BodyMenu_ZSCXST3OZQXUD7.cpp"
#include "RMC_automoc.dir/moc_CameraMenu_NG4Y3ALYYEB5BM.cpp"
#include "RMC_automoc.dir/moc_JointMenu_HWPZHIMNO55G6D.cpp"
#include "RMC_automoc.dir/moc_SensorMenu_XRLGZO2OJRVPOZ.cpp"
#include "RMC_automoc.dir/moc_diagramscene_3KBSRBOGCERML4.cpp"
#include "RMC_automoc.dir/moc_glbox_QCQXULISUWWDBI.cpp"
#include "RMC_automoc.dir/moc_mainwindow_IPGYJP4KIFHGQK.cpp"
