// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "rtcControl.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
rtcControl::RTC_Data::operator>>= (cdrStream &_n) const
{
  _n.marshalString(name,0);
  _n.marshalString(filename,0);
  num >>= _n;

}

void
rtcControl::RTC_Data::operator<<= (cdrStream &_n)
{
  name = _n.unmarshalString(0);
  filename = _n.unmarshalString(0);
  (::CORBA::Short&)num <<= _n;

}

rtcControl::RTCDataInterface_ptr rtcControl::RTCDataInterface_Helper::_nil() {
  return ::rtcControl::RTCDataInterface::_nil();
}

::CORBA::Boolean rtcControl::RTCDataInterface_Helper::is_nil(::rtcControl::RTCDataInterface_ptr p) {
  return ::CORBA::is_nil(p);

}

void rtcControl::RTCDataInterface_Helper::release(::rtcControl::RTCDataInterface_ptr p) {
  ::CORBA::release(p);
}

void rtcControl::RTCDataInterface_Helper::marshalObjRef(::rtcControl::RTCDataInterface_ptr obj, cdrStream& s) {
  ::rtcControl::RTCDataInterface::_marshalObjRef(obj, s);
}

rtcControl::RTCDataInterface_ptr rtcControl::RTCDataInterface_Helper::unmarshalObjRef(cdrStream& s) {
  return ::rtcControl::RTCDataInterface::_unmarshalObjRef(s);
}

void rtcControl::RTCDataInterface_Helper::duplicate(::rtcControl::RTCDataInterface_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

rtcControl::RTCDataInterface_ptr
rtcControl::RTCDataInterface::_duplicate(::rtcControl::RTCDataInterface_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

rtcControl::RTCDataInterface_ptr
rtcControl::RTCDataInterface::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


rtcControl::RTCDataInterface_ptr
rtcControl::RTCDataInterface::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

rtcControl::RTCDataInterface_ptr
rtcControl::RTCDataInterface::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_RTCDataInterface _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_RTCDataInterface* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_RTCDataInterface;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* rtcControl::RTCDataInterface::_PD_repoId = "IDL:rtcControl/RTCDataInterface:1.0";


rtcControl::_objref_RTCDataInterface::~_objref_RTCDataInterface() {
  
}


rtcControl::_objref_RTCDataInterface::_objref_RTCDataInterface(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::rtcControl::RTCDataInterface::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
rtcControl::_objref_RTCDataInterface::_ptrToObjRef(const char* id)
{
  if (id == ::rtcControl::RTCDataInterface::_PD_repoId)
    return (::rtcControl::RTCDataInterface_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::rtcControl::RTCDataInterface::_PD_repoId))
    return (::rtcControl::RTCDataInterface_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for rtcControl::RTCDataInterface::getRTC

// Proxy call descriptor class. Mangled signature:
//  _cboolean_o_crtcControl_mrtcPathSeq
class _0RL_cd_b86b40022299f1cf_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_b86b40022299f1cf_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  rtcControl::rtcPathSeq_var arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_b86b40022299f1cf_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  (const rtcControl::rtcPathSeq&) arg_0 >>= _n;

}

void _0RL_cd_b86b40022299f1cf_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  arg_0 = new rtcControl::rtcPathSeq;
  (rtcControl::rtcPathSeq&)arg_0 <<= _n;

}

const char* const _0RL_cd_b86b40022299f1cf_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_b86b40022299f1cf_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_b86b40022299f1cf_00000000* tcd = (_0RL_cd_b86b40022299f1cf_00000000*)cd;
  rtcControl::_impl_RTCDataInterface* impl = (rtcControl::_impl_RTCDataInterface*) svnt->_ptrToInterface(rtcControl::RTCDataInterface::_PD_repoId);
  tcd->result = impl->getRTC(tcd->arg_0.out());


}

::CORBA::Boolean rtcControl::_objref_RTCDataInterface::getRTC(::rtcControl::rtcPathSeq_out paths)
{
  _0RL_cd_b86b40022299f1cf_00000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_10000000, "getRTC", 7);


  _invoke(_call_desc);
  paths = _call_desc.arg_0._retn();
  return _call_desc.result;


}


//
// Code for rtcControl::RTCDataInterface::createComp

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_cstring
class _0RL_cd_b86b40022299f1cf_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_b86b40022299f1cf_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_b86b40022299f1cf_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);

}

void _0RL_cd_b86b40022299f1cf_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();

}

void _0RL_cd_b86b40022299f1cf_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_b86b40022299f1cf_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_b86b40022299f1cf_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_b86b40022299f1cf_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_b86b40022299f1cf_20000000* tcd = (_0RL_cd_b86b40022299f1cf_20000000*)cd;
  rtcControl::_impl_RTCDataInterface* impl = (rtcControl::_impl_RTCDataInterface*) svnt->_ptrToInterface(rtcControl::RTCDataInterface::_PD_repoId);
  tcd->result = impl->createComp(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean rtcControl::_objref_RTCDataInterface::createComp(const char* name, const char* filename, const char* filepath)
{
  _0RL_cd_b86b40022299f1cf_20000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_30000000, "createComp", 11);
  _call_desc.arg_0 = name;
  _call_desc.arg_1 = filename;
  _call_desc.arg_2 = filepath;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for rtcControl::RTCDataInterface::removeComp

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring
class _0RL_cd_b86b40022299f1cf_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_b86b40022299f1cf_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_b86b40022299f1cf_40000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_b86b40022299f1cf_40000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_b86b40022299f1cf_40000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_b86b40022299f1cf_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_b86b40022299f1cf_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_b86b40022299f1cf_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_b86b40022299f1cf_40000000* tcd = (_0RL_cd_b86b40022299f1cf_40000000*)cd;
  rtcControl::_impl_RTCDataInterface* impl = (rtcControl::_impl_RTCDataInterface*) svnt->_ptrToInterface(rtcControl::RTCDataInterface::_PD_repoId);
  tcd->result = impl->removeComp(tcd->arg_0);


}

::CORBA::Boolean rtcControl::_objref_RTCDataInterface::removeComp(const char* name)
{
  _0RL_cd_b86b40022299f1cf_40000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_50000000, "removeComp", 11);
  _call_desc.arg_0 = name;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for rtcControl::RTCDataInterface::getCompList

// Proxy call descriptor class. Mangled signature:
//  _cboolean_o_crtcControl_mRTC__List
class _0RL_cd_b86b40022299f1cf_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_b86b40022299f1cf_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  rtcControl::RTC_List_var arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_b86b40022299f1cf_60000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  (const rtcControl::RTC_List&) arg_0 >>= _n;

}

void _0RL_cd_b86b40022299f1cf_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  arg_0 = new rtcControl::RTC_List;
  (rtcControl::RTC_List&)arg_0 <<= _n;

}

const char* const _0RL_cd_b86b40022299f1cf_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_b86b40022299f1cf_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_b86b40022299f1cf_60000000* tcd = (_0RL_cd_b86b40022299f1cf_60000000*)cd;
  rtcControl::_impl_RTCDataInterface* impl = (rtcControl::_impl_RTCDataInterface*) svnt->_ptrToInterface(rtcControl::RTCDataInterface::_PD_repoId);
  tcd->result = impl->getCompList(tcd->arg_0.out());


}

::CORBA::Boolean rtcControl::_objref_RTCDataInterface::getCompList(::rtcControl::RTC_List_out names)
{
  _0RL_cd_b86b40022299f1cf_60000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_70000000, "getCompList", 12);


  _invoke(_call_desc);
  names = _call_desc.arg_0._retn();
  return _call_desc.result;


}

rtcControl::_pof_RTCDataInterface::~_pof_RTCDataInterface() {}


omniObjRef*
rtcControl::_pof_RTCDataInterface::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::rtcControl::_objref_RTCDataInterface(ior, id);
}


::CORBA::Boolean
rtcControl::_pof_RTCDataInterface::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::rtcControl::RTCDataInterface::_PD_repoId))
    return 1;
  
  return 0;
}

const rtcControl::_pof_RTCDataInterface _the_pof_rtcControl_mRTCDataInterface;

rtcControl::_impl_RTCDataInterface::~_impl_RTCDataInterface() {}


::CORBA::Boolean
rtcControl::_impl_RTCDataInterface::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getRTC")) {

    _0RL_cd_b86b40022299f1cf_00000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_10000000, "getRTC", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "createComp")) {

    _0RL_cd_b86b40022299f1cf_20000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_30000000, "createComp", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "removeComp")) {

    _0RL_cd_b86b40022299f1cf_40000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_50000000, "removeComp", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getCompList")) {

    _0RL_cd_b86b40022299f1cf_60000000 _call_desc(_0RL_lcfn_b86b40022299f1cf_70000000, "getCompList", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
rtcControl::_impl_RTCDataInterface::_ptrToInterface(const char* id)
{
  if (id == ::rtcControl::RTCDataInterface::_PD_repoId)
    return (::rtcControl::_impl_RTCDataInterface*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::rtcControl::RTCDataInterface::_PD_repoId))
    return (::rtcControl::_impl_RTCDataInterface*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
rtcControl::_impl_RTCDataInterface::_mostDerivedRepoId()
{
  return ::rtcControl::RTCDataInterface::_PD_repoId;
}

POA_rtcControl::RTCDataInterface::~RTCDataInterface() {}

